// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exvvwmzrkgnmlqyeahsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4dnZ3bXpya2dubWxxeWVhaHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjMzMjcsImV4cCI6MjA3MjM5OTMyN30.JdLT-NKehr1jz2q7KKwChg17lNvOsmZK3t2rEasmWvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});